// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TunaPianoAPI.Migrations
{
    [DbContext(typeof(TunaPianoDbContext))]
    [Migration("20240305021910_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TunaPianoAPI.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            Bio = "Ariana Grande-Butera is an American singer, songwriter, and actress. Regarded as a pop icon, she is noted as an influential figure in popular music and as one of the most prominent vocalists of her generation for her four-octave vocal range and signature whistle register.",
                            Name = "Ariana Grande"
                        },
                        new
                        {
                            Id = 2,
                            Age = 82,
                            Bio = "Carole King Klein is an American singer-songwriter and musician who has been active since 1958. One of the most successful female songwriters of the latter half of the 20th century in the US, she wrote or co-wrote 118 pop hits on the Billboard Hot 100.",
                            Name = "Carole King"
                        });
                });

            modelBuilder.Entity("TunaPianoAPI.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic"
                        });
                });

            modelBuilder.Entity("TunaPianoAPI.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Positions",
                            ArtistId = 1,
                            Length = 3,
                            Title = "shut up"
                        },
                        new
                        {
                            Id = 2,
                            Album = "thank u, next",
                            ArtistId = 1,
                            Length = 2,
                            Title = "thank u, next"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Tapestry",
                            ArtistId = 2,
                            Length = 4,
                            Title = "I Fell the Earth Move"
                        },
                        new
                        {
                            Id = 4,
                            Album = "Tapestry",
                            ArtistId = 2,
                            Length = 4,
                            Title = "It's Too Late"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
